project_name: kyverno 
release:
  github:
    owner: kyverno 
    name: kyverno 
builds:
  - id: kyverno 
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/cli/kubectl-kyverno/main.go
    ldflags: -s -w
      -X github.com/kyverno/kyverno/pkg/version.BuildVersion={{ .Version }}
      -X github.com/kyverno/kyverno/pkg/version.BuildHash={{ .FullCommit }}
      -X github.com/kyverno/kyverno/pkg/version.BuildTime={{ .Timestamp }}
archives:
  - id: kyverno 
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip